INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('bulbasaur', 'Bulbasaur', 1,0,1),
('ivysaur', 'Ivysaur', 1, 0, 1),
('venusaur', 'Venusaur', 1, 0, 1),
('charmander', 'Charmander', 1, 0, 1),
('charmeleon', 'Charmeleon', 1, 0, 1),
('charizard', 'Charizard', 1, 0, 1),
('squirtle', 'Squirtle', 1, 0, 1),
('wartortle', 'Wartortle', 1, 0, 1),
('blatoise', 'Blatoise', 1, 0, 1),
('caterpie', 'Caterpie', 1, 0, 1),
('metapod', 'Metapod', 1, 0, 1),
('butterfree', 'Butterfree', 1 , 0, 1),
('weedle','Weedle', 1, 0, 1),
('kakuna', 'Kakuna', 1, 0, 1),
('beedrill', 'Beedrill', 1, 0, 1),
('pidgey', 'Pidgey', 1, 0, 1),
('pidgeotto', 'Pidgeotto', 1, 0, 1),
('rattata', 'Rattata', 1, 0, 1),
('raticate', 'Raticate', 1, 0, 1),
('spearow', 'Spearow', 1, 0, 1),
('fearow', 'Fearow', 1, 0, 1),
('ekans', 'Ekans', 1, 0, 1),
('arbok', 'Arbok', 1, 0, 1),
('pikachu', 'Pikachu', 1, 0, 1),
('raichu', 'Raichu', 1, 0, 1),
('sandshrew', 'Sandshrew', 1, 0, 1),
('sandslash', 'Sandslash', 1, 0, 1),
('nidoran', 'Nidoran', 1, 0, 1),
('nidorina', 'Nidorina', 1, 0, 1),
('nidoqueen', 'Nidoqueen', 1, 0, 1),
('nidoking', 'Nidoking', 1, 0, 1),
('clefairy', 'Clefairy', 1, 0, 1),
('clefable', 'Clefable', 1, 0, 1),
('vulpix', 'Vulpix', 1, 0, 1),
('ninetales', 'Ninetales', 1, 0, 1),
('jigglypuff', 'Jigglypuff', 1, 0, 1),
('wigglytuff', 'Wigglytuff', 1, 0, 1),
('zubat', 'Zubat', 1, 0, 1),
('golbat', 'Golbat', 1, 0, 1),
('oddish', 'Oddish', 1, 0, 1),
('gloom', 'Gloom', 1, 0, 1),
('vileplume', 'Vileplume', 1, 0, 1),
('paras', 'Paras', 1, 0, 1),
('parasect', 'Parasect', 1, 0, 1),
('venonat', 'Venonat', 1, 0, 1),
('venomoth', 'Venomoth', 1, 0, 1),
('diglett', 'Diglett', 1, 0, 1),
('dugtrio', 'Dugtrio', 1, 0, 1),
('mewoth', 'Mewoth', 1, 0, 1),
('persian', 'Persian', 1, 0, 1),
('psyduck', 'Psyduck', 1, 0, 1),
('golduck', 'Golduck', 1, 0, 1),
('geodude', 'Geodude', 1, 0, 1),
('graveler', 'Graveler', 1, 0, 1),
('golem', 'Golem', 1, 0, 1),
('ponyta', 'Ponyta', 1, 0, 1),
('rapidash', 'Rapidash',1, 0, 1),
('slowpoke', 'Slowpoke', 1, 0, 1),
('slowbro', 'Slowbro', 1, 0, 1),
('magnemite', 'Magnemite', 1, 0, 1),
('magneton', 'Magneton', 1, 0, 1),
('farfetchd','Farfetchd', 1, 0, 1),
('doduo', 'Doduo',1, 0, 1),
('dodrio', 'Dodrio', 1, 0, 1),
('seel', 'Seel', 1, 0, 1),
('dewgong', 'Dewgong', 1, 0, 1),
('grimer', 'Grimer', 1, 0, 1),
('muk', 'Muk', 1, 0, 1),
('shellder', 'Shellder', 1, 0, 1),
('cloyster', 'Cloyster', 1, 0, 1),
('gastly', 'Gastly', 1, 0, 1),
('haunter', 'Haunter', 1, 0, 1),
('mankey', 'Mankey', 1, 0, 1),
('primeape','Primeape', 1, 0, 1),
('growlithe', 'Growlithe', 1, 0, 1),
('arcanine', 'Arcanine', 1, 0, 1),
('poliwag', 'Poliwag', 1, 0, 1),
('poliwhirl', 'Poliwhirl', 1, 0, 1),
('poliwrath', 'Poliwrath', 1, 0, 1),
('abra', 'Abra', 1, 0, 1),
('kadabra', 'Kadabra', 1, 0, 1),
('alakazam', 'Alakazam', 1, 0, 1),
('machop', 'Machop', 1, 0, 1),
('machoke', 'Machoke', 1, 0, 1),
('machamp', 'Machamp', 1, 0, 1),
('bellsprout', 'Bellsprout', 1, 0, 1),
('weepinbell', 'Weepinbell', 1, 0, 1),
('victreebel', 'Victreebel', 1, 0, 1),
('tentacool', 'Tentacool', 1, 0, 1),
('tentacruel', 'Tentacruel', 1, 0, 1),
('gengar', 'Gengar', 1, 0, 1),
('onix', 'Onix', 1, 0, 1),
('drowzee', 'drowzee', 1, 0, 1),
('hypno', 'Hypno', 1, 0, 1),
('krabby', 'Krabby', 1, 0, 1),
('kingler', 'Kingler', 1, 0, 1),
('voltorb','Voltorb', 1, 0, 1),
('electrode', 'Electrode', 1, 0, 1),
('exeggcute', 'Exeggcute', 1, 0, 1),
('exeggutor', 'Exeggutor', 1, 0, 1),
('cubone', 'Cubone', 1, 0, 1),
('marowak', 'Marowak', 1, 0, 1),
('hitmonlee', 'Hitmonlee', 1, 0, 1),
('hitmonchan', 'Hitmonchan', 1, 0, 1),
('lickitung', 'Lickitung', 1, 0, 1),
('koffing', 'Koffing', 1, 0, 1),
('weezing', 'Weezing', 1, 0, 1),
('rhyhorn', 'Rhyhorn', 1, 0, 1),
('rhydon', 'Rhydon', 1, 0, 1),
('chansey', 'Chansey', 1, 0, 1),
('tangela', 'Tangela', 1, 0, 1),
('kangaskhan', 'kangaskhan', 1, 0, 1),
('horsea', 'Horsea', 1, 0, 1),
('seadra', 'Seadra', 1, 0, 1),
('goldeen','Goldeen', 1, 0, 1),
('seaking', 'Seaking', 1, 0, 1),
('staryu', 'Staryu', 1, 0, 1),
('starmie', 'Starmie', 1, 0, 1),
('mr. mime', 'Mr. mime', 1, 0, 1),
('scyther', 'Scyther', 1, 0, 1),
('jynx', 'Jynx', 1, 0, 1),
('electabuzz', 'Electabuzz', 1, 0, 1),
('magmar', 'Magmar', 1, 0, 1),
('pinsir', 'Pinsir', 1, 0, 1),
('tauros', 'Tauros', 1, 0, 1),
('magikarp', 'Magikarp', 1, 0, 1),
('gyarados', 'Gyarados', 1, 0, 1),
('lapras', 'Lapras', 1, 0, 1),
('ditto', 'Ditto', 1, 0, 1),
('eevee', 'Eevee', 1, 0, 1),
('vaporeon', 'Vaporeon', 1, 0, 1),
('jolteon', 'Jolteon', 1, 0, 1),
('flareon', 'Flareon', 1, 0, 1),
('porygon', 'Porygon', 1, 0, 1),
('omanyte', 'Omanyte', 1, 0, 1),
('omastar', 'Omastar', 1, 0, 1),
('kabutops', 'Kabutops', 1, 0, 1),
('aerodactyl', 'Aerodactyl', 1, 0, 1),
('snorlax', 'Snorlax', 1, 0, 1),
('articuno', 'Articuno', 1, 0, 1),
('zapdos', 'Zapdos', 1, 0, 1),
('moltres', 'Moltres', 1, 0, 1),
('dratini', 'Dratini', 1, 0, 1),
('dragonair', 'Dragonair', 1, 0, 1),
('dragonite', 'Dragonite', 1, 0, 1),
('mewtwo', 'Mewtwo', 1, 0, 1),
('mew', 'Mew', 1, 0, 1),
('togepi', 'Togepi', 1, 0, 1),
('boulderBadge', 'Boulder Badge', 1, 0, 1),
('cascadeBadge', 'Cascade Badge', 1, 0, 1),
('thunderBadge', 'Thunder Badge', 1, 0, 1),
('rainbowBadge', 'Rainbow Badge', 1, 0, 1),
('soulBadge', 'Soul Badge', 1, 0, 1),
('marshBadge', 'Marsh Badge', 1, 0, 1),
('volcanoBadge', 'Volcano Badge', 1, 0, 1),
('earthBadge', 'Earth Badge', 1, 0, 1),
('trophyBadge', 'Pokemon League Trophy', 1, 0, 1),
('recipe_boulderBadge', 'Boulder Badge Blueprint', 1, 0, 1),
('recipe_cascadeBadge', 'Cascade Badge Blueprint', 1, 0, 1),
('recipe_thunderBadge', 'Thunder Badge Blueprint', 1, 0, 1),
('recipe_rainbowBadge', 'Rainbow Badge Blueprint', 1, 0, 1),
('recipe_soulBadge', 'Soul Badge Blueprint', 1, 0, 1),
('recipe_marshBadge', 'Marsh Badge Blueprint', 1, 0, 1),
('recipe_volcanoBadge', 'Volcano Badge Blueprint', 1, 0, 1),
('recipe_earthBadge', 'Earth Badge Blueprint', 1, 0, 1),
('recipe_trophyBadge', 'Pokemon League Trophy Blueprint', 1, 0, 1);
